### ISSUE TITLE
Bayesian first aid is amazing, can you extend it please

### ISSUE THREAD

**Issue by FarrelBuch** [rasmusab/bayesian_first_aid#14]
Do you have any plans for venturing into linear regression, multiple linear regression, logistic regression and multiple logistic regression and survival analysis. I personally do not know how to code it but I want to encourage you or anyone else you can coopt to write with you.

**Comment by palday** [comment]
The [`rstanarm` package](https://github.com/stan-dev/rstanarm) does the [regression part](http://andrewgelman.com/2016/01/14/rstanarm-and-more/).

**Comment by rasmusab** [comment]
I still have plans to extend BayesianFirstAid slightly, and eventually get it onto CRAN, but regression analysis is unfortunately not part of that plan. The packages @palday mentions are excelent!
