### ISSUE TITLE
summary information into dataframe ?

### ISSUE THREAD

**Issue by drbenvincent** [rasmusab/bayesian_first_aid#15]
I am new to R, so apologies if this has a simple answer. Let's say I've fitted a model... rather than printing out the summary information using `summary(fit)`, is it possible to assign the summary stats (i.e. mean     sd  HDIlo  HDIup etc) to a data frame? I'm attempting to plot posterior summary information in RMarkdown/Knitr, so just wondered how I can extract the info into a variable.

PS, great repo
Thanks!

**Comment by rasmusab** [comment]
Hi Benjamin,

That should be as simple as `d <- summary(fit)`. Now d contains a large data frame with different summary information regarding the fit.

**Comment by drbenvincent** [comment]
I'm getting a successful fit, and am doing exactly as you say, but the contents of d is `NULL`

**Comment by rasmusab** [comment]
Which bayes. function ate you running?

On Friday, 10 June 2016, Benjamin T. Vincent <notifications@github.com>
wrote:

> I'm getting a successful fit, and am doing exactly as you say, but the
> contents of d is NULL
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rasmusab/bayesian_first_aid/issues/15#issuecomment-225182734>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA9aQDTWtrTVQRx98WTaX4CPqgtXOM-2ks5qKWdygaJpZM4IyXY7>
> .
>


-- 
/Rasmus

**Comment by drbenvincent** [comment]
`bayes.cor.test()`

Everything seems fine, it prints summary to the screen, and I can call `plot()` and `summary()` just fine.

**Comment by rasmusab** [comment]
Right, turns out I was a 100% wrong here. You can get that dataframe by doing this:
```
d <- summary(fit)
d$stats
```

But I will change it so that summary(fit) also returns the `d$stats`, so let's keep the issue open until I fix that.

**Comment by drbenvincent** [comment]
Hmm, I'm still getting `d` as entirely `NULL`, even with `d$stats`.

**Comment by rasmusab** [comment]
Ah, that was just my copy-paste that failed me, here is what I meant: :)

```
d <- bayes.cor.test(...)
d$stats
```

**Comment by drbenvincent** [comment]
superb. That works for me. Will leave issue open as requested. Thanks for your help 👍

**Comment by rasmusab** [comment]
`summary(fit)` should now also return a matrix with summary statistics of the posterior.
