### ISSUE TITLE
paired bayes.t.test differs quite a lot from standard paired t.test

### ISSUE THREAD

**Issue by silberzwiebel** [rasmusab/bayesian_first_aid#20]
Hi,

I've just discovered your nice R package because I was searching for a Bayesian estimation applicable for data for which you would normally use a paired t.test.
My data consists of acceptability ratings given my the same subjects in two differing experimental conditions. (The acceptability ratings might actually be better treated as ordinal data but I'm treating them as metrical).
Using a default
`t.test(d$condition1, d$condition2, paired=TRUE)`

gives this result:

```
Paired t-test

data:  d$condition1 and d$condition2
t = -9.3649, df = 407, p-value < 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.7561958 -0.4938042
sample estimates:
mean of the differences 
                 -0.625 
```

As I read this (and the data also looks like this), this is quite good evidence that people rated stimuli in condition1 lower than in condition2.

However, if I'm using

```
bayes.t.test(d$condition1, d$condition2, paired= TRUE)
Bayesian estimation supersedes the t test (BEST) - paired samples

data: d$condition1 and d$condition2, n = 408

  Estimates [95% credible interval]
mean paired difference: -5.6e-07 [-0.00012, 0.00013]
sd of the paired differences: 0.0014 [0.0013, 0.0014]

The mean difference is more than 0 by a probability of 0.497 
and less than 0 by a probability of 0.503 
```

These results tell  a complete opposite: Apparently, there is no difference under the two conditions. What looks strange to me is that the estimated mean and SD do not match the mean and SD of the data at all (which is M =  0.625 and SD = 1.35)

Since I'm just discovering Bayesian statistics, I wonder if I'm something wrong or if there is some bug in your R package.

You may find the data for the next 2 weeks under [this link.](https://kartoffelsalat.ddns.net:8001/f/8c61d3e4e9/?raw=1)

**Comment by silberzwiebel** [comment]
After looking closer at the data and finally modeling it with a normal likelihood instead of the t-distribution proposed in the BEST approach, I got acceptable results (in terms of: closer to the standard t-test).
Apparently, the t distribution has problems to fit my data. See also the issue I filed at the BEST package: https://github.com/mikemeredith/BEST/issues/6

**Comment by rasmusab** [comment]
Hmmm, yeah, I wouldn't call it a bug. But the model seems to get "tricked" by the large number of values that are exactly zero, which makes it very probable that the nu parameter is very close to zero, which makes it very likely that mu and sigma are small. By adding noise to your data the `bayes.t.test` actually produces more reasonable results. I'm going to close this issue now, but big thanks for reporting this! And I'm going to think about whether I should make some changes to the prior for the nu parameter to nudge it away from 0.0`.

**Comment by silberzwiebel** [comment]
Thanks for your answer. I think the [comment I just left here](https://github.com/mikemeredith/BEST/issues/6#issuecomment-276908810) also applies for this issue.
