### ISSUE TITLE
Any way to turn off the output from activating the library?

### ISSUE THREAD

**Issue by svannoy** [rasmusab/bayesian_first_aid#8]
Hi,

First, thanks so much for producing this library, it's great.

I'm using the code and producing an html file via Knitr in RStudio. When I activate the library, using:
  library(BayesianFirstAid, warn.conflicts=FALSE, verbose=FALSE, quietly = TRUE)
I get the following output in my html file:
## Loaded modules: basemod,bugs

I'm not very familiar with html, I'm sure I could edit that out, but it would be nice to just get it to load silently.

Thanks for any help you can provide.

Steven

**Comment by cheuerde** [comment]
Hi,

that message comes from 'rjags'.
You can surpress is like this:

suppressMessages(library(BayesianFirstAid))

taken from here: 
http://stackoverflow.com/questions/6279808/r-suppress-startupmessages-from-dependency

Best,

Claas

**Comment by svannoy** [comment]
Hi, that worked, thank you!

Steven

*****************************
@stevenvannoy
stevenvannoy.wordpress.com

**Comment by rasmusab** [comment]
Thanks cheuerde fo the solution!
